language: java
jdk:
  - oraclejdk8

# plugin that downloads the latest JDK version (required for new JavaFx features)
addons:
  apt:
    packages:
      - oracle-java8-installer

# --- 
# Flo:
# It would be cool to test on multiple platforms but changing JDK version 
# does not yet work for OSX: https://github.com/travis-ci/travis-ci/issues/2317
# --- 

#os:
#  - linux
#  - osx
